name: Deploy Unity WebGL (Firebase) to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 🔧 Replace placeholders in docs/index.html with your GitHub secrets
      - name: Inject Firebase secrets
        run: |
          sed -i "s|\"API_KEY\"|\"${{ secrets.API_KEY }}\"|g" docs/index.html
          sed -i "s|\"AUTH_DOMAIN\"|\"${{ secrets.AUTH_DOMAIN }}\"|g" docs/index.html
          sed -i "s|\"PROJECT_ID\"|\"${{ secrets.PROJECT_ID }}\"|g" docs/index.html
          sed -i "s|\"STORAGE_BUCKET\"|\"${{ secrets.STORAGE_BUCKET }}\"|g" docs/index.html
          sed -i "s|\"MESSAGING_SENDER_ID\"|\"${{ secrets.MESSAGING_SENDER_ID }}\"|g" docs/index.html
          sed -i "s|\"APP_ID\"|\"${{ secrets.APP_ID }}\"|g" docs/index.html
          sed -i "s|\"MEASUREMENT_ID\"|\"${{ secrets.MEASUREMENT_ID }}\"|g" docs/index.html
          echo "Injected Firebase secrets successfully."

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
